<script setup lang="ts">
type InvoiceItem = {
  id: string
  position: number
  description: string
  quantity: number | null
  unit_price: number | null
  amount: number
}

type Props = {
  vendor: string | null
  vendorAddress?: string | null
  invoiceNumber?: string | null
  invoiceDate?: string | null
  createdAt?: string | null
  currency: string | null
  subtotal: number | null
  tax: number | null
  taxRate?: number | null
  total: number | null
  items: InvoiceItem[]
  invoiceId: string
  voidedAt?: string | null
}

const props = defineProps<Props>()

function fmt(n: number | null): string {
  return n == null ? '—' : n.toFixed(2)
}

function fmtWithSymbol(n: number | null): string {
  return formatAmount(n, props.currency)
}

const shortId = computed(() => props.invoiceId.slice(0, 8).toUpperCase())
const itemCount = computed(() => props.items.length)
const isVoided = computed(() => !!props.voidedAt)
const voidedDateLabel = computed(() => formatLongDate(props.voidedAt))
</script>

<template>
  <article
    class="dinv"
    :class="{ 'dinv-is-voided': isVoided }"
    :aria-label="isVoided ? 'Digital invoice (voided)' : 'Digital invoice'"
  >
    <div
      v-if="isVoided"
      class="dinv-void-stamp"
      role="img"
      aria-label="Voided invoice"
    >
      <span class="dinv-void-stamp-text">ANULADA</span>
      <span v-if="voidedDateLabel !== '—'" class="dinv-void-stamp-date mono">
        {{ voidedDateLabel }}
      </span>
    </div>

    <header class="dinv-head">
      <div class="dinv-brand">
        <img src="~/assets/images/logo-1.png" alt="" class="dinv-logo" />
        <span class="dinv-brand-name">scan-me</span>
      </div>
      <div class="dinv-head-right">
        <span v-if="isVoided" class="dinv-void-badge mono" aria-hidden="true">
          ⊘ ANULADA
        </span>
        <div class="dinv-stamp">
          <span class="dinv-stamp-label">Invoice</span>
          <span class="dinv-stamp-id mono">#{{ shortId }}</span>
        </div>
      </div>
    </header>

    <div class="dinv-divider" />

    <section class="dinv-meta">
      <div class="dinv-meta-block">
        <span class="dinv-key mono">Issued by</span>
        <span class="dinv-val">{{ vendor || 'Unknown vendor' }}</span>
        <span v-if="vendorAddress" class="dinv-sub">{{ vendorAddress }}</span>
      </div>
      <div class="dinv-meta-block r">
        <span class="dinv-key mono">Date</span>
        <span class="dinv-val">{{ formatLongDate(invoiceDate, createdAt) }}</span>
        <span v-if="invoiceNumber" class="dinv-sub mono">№ {{ invoiceNumber }}</span>
      </div>
    </section>

    <div class="dinv-divider dashed" />

    <section v-if="items.length" class="dinv-items">
      <div class="dinv-row dinv-row-head mono">
        <span class="dinv-col-desc">Description</span>
        <span class="dinv-col-qty">Qty</span>
        <span class="dinv-col-unit">Unit</span>
        <span class="dinv-col-amt">Amount</span>
      </div>

      <div
        v-for="it in items"
        :key="it.id"
        class="dinv-row"
      >
        <span class="dinv-col-desc">{{ it.description }}</span>
        <span class="dinv-col-qty mono">{{ it.quantity ?? '—' }}</span>
        <span class="dinv-col-unit mono">{{ fmt(it.unit_price) }}</span>
        <span class="dinv-col-amt mono">{{ fmt(it.amount) }}</span>
      </div>
    </section>

    <section v-else class="dinv-empty">
      <span class="mono">No line items extracted</span>
    </section>

    <div class="dinv-divider dashed" />

    <section class="dinv-totals">
      <div v-if="subtotal != null" class="dinv-trow">
        <span class="dinv-key mono">Subtotal</span>
        <span class="dinv-val mono">{{ fmt(subtotal) }}</span>
      </div>
      <div v-if="tax != null" class="dinv-trow">
        <span class="dinv-key mono">
          Tax<template v-if="taxRate != null"> · {{ Math.round(taxRate * 100) }}%</template>
        </span>
        <span class="dinv-val mono">{{ fmt(tax) }}</span>
      </div>
      <div class="dinv-trow grand">
        <span class="dinv-key mono">Total</span>
        <span class="dinv-val">{{ fmtWithSymbol(total) }}</span>
      </div>
    </section>

    <footer class="dinv-foot">
      <span class="mono">Generated by scan-me</span>
      <span class="mono">{{ itemCount }} {{ itemCount === 1 ? 'item' : 'items' }}</span>
    </footer>

    <aside class="dinv-notice" role="note" aria-label="Legal notice">
      <span class="dinv-notice-tag mono">Notice</span>
      <p class="dinv-notice-body">
        This document is <strong>not a legal invoice</strong>. It is a digital
        reference generated by scan-me from a user-uploaded receipt and is
        provided for record-keeping purposes only. scan-me makes no
        representation as to its accuracy and accepts no responsibility for the
        use, interpretation, or management of this digital invoice.
      </p>
    </aside>
  </article>
</template>

<style scoped>
.dinv {
  background: var(--color-snow);
  border: 1px solid var(--color-mist);
  border-radius: var(--radius-lg);
  padding: var(--space-8) var(--space-8) var(--space-6);
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
  color: var(--color-ink);
  font-family: var(--font-text);
  position: relative;
}

.dinv::before,
.dinv::after {
  content: '';
  position: absolute;
  left: var(--space-4);
  right: var(--space-4);
  height: 0;
  border-top: 1px dashed var(--color-mist);
}
.dinv::before { top: 0; }
.dinv::after { bottom: 0; }

.dinv-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
}
.dinv-brand {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
}
.dinv-logo {
  height: 22px;
  width: auto;
  display: block;
}
.dinv-brand-name {
  font-weight: 600;
  letter-spacing: -0.02em;
  font-size: 15px;
}
.dinv-head-right {
  display: inline-flex;
  align-items: center;
  gap: var(--space-3);
}
.dinv-void-badge {
  display: inline-flex;
  align-items: center;
  padding: var(--space-1) var(--space-3);
  border-radius: var(--radius-pill);
  border: 1px solid var(--color-error);
  background: color-mix(in srgb, var(--color-error) 14%, transparent);
  color: var(--color-error);
  font-size: 10px;
  letter-spacing: 0.14em;
  font-weight: 600;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
.dinv-stamp {
  display: inline-flex;
  flex-direction: column;
  align-items: flex-end;
  line-height: 1.1;
}
.dinv-stamp-label {
  font-family: var(--font-mono);
  font-size: 10px;
  color: var(--color-graphite);
  letter-spacing: 0.12em;
  text-transform: uppercase;
}
.dinv-stamp-id {
  margin-top: var(--space-1);
  font-size: 12px;
  color: var(--color-ink);
  letter-spacing: 0.06em;
}

.dinv-divider {
  height: 0;
  border-top: 1px solid var(--color-mist);
}
.dinv-divider.dashed {
  border-top-style: dashed;
}

.dinv-meta {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-4);
}
.dinv-meta-block {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}
.dinv-meta-block.r {
  align-items: flex-end;
  text-align: right;
}
.dinv-key {
  font-size: 10px;
  color: var(--color-graphite);
  letter-spacing: 0.12em;
  text-transform: uppercase;
}
.dinv-val {
  font-size: var(--text-body-sm);
  font-weight: 500;
  letter-spacing: -0.01em;
  color: var(--color-ink);
}
.dinv-sub {
  font-size: 11px;
  color: var(--color-graphite);
  letter-spacing: 0.02em;
}

.dinv-items {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.dinv-row {
  display: grid;
  grid-template-columns: 1.6fr 0.4fr 0.6fr 0.7fr;
  gap: var(--space-3);
  align-items: baseline;
  font-size: 13px;
  padding: 6px 0;
  border-bottom: 1px dotted var(--color-mist);
}
.dinv-row:last-child {
  border-bottom: none;
}
.dinv-row-head {
  font-size: 10px;
  color: var(--color-graphite);
  letter-spacing: 0.1em;
  text-transform: uppercase;
  padding-bottom: var(--space-1);
  border-bottom: 1px solid var(--color-mist);
}
.dinv-col-desc { letter-spacing: -0.005em; }
.dinv-col-qty,
.dinv-col-unit,
.dinv-col-amt {
  text-align: right;
}

.dinv-empty {
  padding: var(--space-3) 0;
  text-align: center;
  font-size: 11px;
  color: var(--color-graphite);
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.dinv-totals {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.dinv-trow {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  font-size: 13px;
}
.dinv-trow .dinv-key {
  text-transform: none;
  letter-spacing: 0.04em;
  font-size: 11px;
}
.dinv-trow.grand {
  margin-top: var(--space-2);
  padding-top: var(--space-3);
  border-top: 1px solid var(--color-mist);
}
.dinv-trow.grand .dinv-key {
  font-size: 12px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--color-ink);
}
.dinv-trow.grand .dinv-val {
  font-family: var(--font-display);
  font-size: 20px;
  font-weight: 600;
  letter-spacing: -0.025em;
}

.dinv-foot {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 10px;
  color: var(--color-graphite);
  letter-spacing: 0.1em;
  text-transform: uppercase;
  padding-top: var(--space-1);
}

.dinv-notice {
  display: none;
  margin-top: var(--space-1);
  padding: var(--space-3) var(--space-4);
  border: 1px solid var(--color-mist);
  border-radius: var(--radius-md);
  background: var(--color-fog);
  gap: var(--space-3);
  align-items: flex-start;
}
@media print {
  .dinv-notice {
    display: flex;
  }
}
.dinv-notice-tag {
  flex-shrink: 0;
  font-size: 10px;
  color: var(--color-graphite);
  letter-spacing: 0.12em;
  text-transform: uppercase;
  padding: 2px var(--space-2);
  border: 1px solid var(--color-mist);
  border-radius: var(--radius-pill);
  background: var(--color-snow);
  margin-top: 1px;
}
.dinv-notice-body {
  margin: 0;
  font-size: 11px;
  line-height: 1.5;
  color: var(--color-graphite);
  letter-spacing: -0.005em;
}
.dinv-notice-body strong {
  color: var(--color-ink);
  font-weight: 600;
}

@media (max-width: 768px) {
  .dinv { padding: var(--space-6) var(--space-5) var(--space-5); }
  .dinv-row {
    grid-template-columns: 1.4fr 0.4fr 0.6fr 0.7fr;
    gap: var(--space-2);
    font-size: 12px;
  }
  .dinv-trow.grand .dinv-val { font-size: 18px; }
}

/* Voided state */
.dinv-is-voided {
  overflow: hidden;
}
.dinv-is-voided .dinv-val,
.dinv-is-voided .dinv-col-amt,
.dinv-is-voided .dinv-trow.grand .dinv-val {
  text-decoration: line-through;
  text-decoration-color: var(--color-error);
  text-decoration-thickness: 1.5px;
}
.dinv-void-stamp {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) rotate(-14deg);
  padding: var(--space-3) var(--space-10);
  border: 4px double var(--color-error);
  border-radius: var(--radius-md);
  color: var(--color-error);
  background: color-mix(in srgb, var(--color-snow) 70%, transparent);
  pointer-events: none;
  z-index: 2;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--space-1);
  text-align: center;
  font-family: var(--font-display);
  opacity: 0.92;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
.dinv-void-stamp-text {
  font-size: 36px;
  font-weight: 700;
  letter-spacing: 0.18em;
  line-height: 1;
}
.dinv-void-stamp-date {
  font-size: 11px;
  letter-spacing: 0.16em;
  opacity: 0.85;
}
@media print {
  .dinv-void-stamp {
    opacity: 1;
    background: transparent;
  }
}
</style>
